version: "3"
services:
  service_a:
    # replace username/repo:tag with your name and image details
    image: flask-service:latest 
    environment:
      - VIRTUAL_HOST=service_a.local
      - SERVICE_NAME=service_a
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  service_b:
    image: flask-service:latest
    environment:
      - VIRTUAL_HOST=service_b.local
      - SERVICE_NAME=service_b
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  foo:
    image: flask-service:latest
    environment:
      - VIRTUAL_HOST=foo.local
      - SERVICE_NAME=foo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet2
  bar:
    image: flask-service:latest
    environment:
      - VIRTUAL_HOST=bar.local
      - SERVICE_NAME=bar
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet2
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webnet
      - webnet2

networks:
  webnet:
  webnet2:
