version: "3"
services:
  a:
    # replace username/repo:tag with your name and image details
    image: service_a:latest 
    container_name: service_a
    environment:
      - VIRTUAL_HOST=service_a.local
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  b:
    image: service_b
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "81:80"
    networks:
      - webnet
  foo:
    image: foo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "82:80"
    networks:
      - webnet2
  bar:
    image: bar
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "83:80"
    networks:
      - webnet2

networks:
  webnet:
  webnet2:
